services:
  roach1:
    image: cockroachdb/cockroach:v24.2.3
    container_name: roach1
    hostname: roach1
    networks:
      - roachnet
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach1:/cockroach/cockroach-data
    command: 
      start
      --advertise-addr=roach1:26357 
      --http-addr=roach1:8080
      --listen-addr=roach1:26357
      --sql-addr=roach1:26257
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357
    cpuset: '0'

  roach2:
    image: cockroachdb/cockroach:v24.2.3
    container_name: roach2
    hostname: roach2
    networks:
      - roachnet
    volumes:
      - roach2:/cockroach/cockroach-data
    command:
      start
      --advertise-addr=roach2:26357
      --http-addr=roach2:8081
      --listen-addr=roach2:26357
      --sql-addr=roach2:26258
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357
    cpuset: '1'

  roach3:
    image: cockroachdb/cockroach:v24.2.3
    container_name: roach3
    hostname: roach3
    networks:
      - roachnet
    volumes:
      - roach3:/cockroach/cockroach-data
    command:
      start
      --advertise-addr=roach3:26357
      --http-addr=roach3:8082
      --listen-addr=roach3:26357
      --sql-addr=roach3:26259
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357
    cpuset: '2'

networks:
  roachnet:
    driver: bridge

volumes:
  roach1:
  roach2:
  roach3:

